---
- name: Ensure we have ~/.ansible
  tags:
    - always
    - lab
  ansible.builtin.file:
    mode: '755'
    path: ~/.ansible/roles
    state: directory

- name: Clone ansible-role-redhat-subscription
  ansible.builtin.git:
    dest: ~/.ansible/roles/redhat-subscription
    repo: https://opendev.org/openstack/ansible-role-redhat-subscription
    update: "{{ update_rhsm | bool }}"
    # Upstream repo has been retired, this is the latest commit
    version: eefe5019238a7b88bda0a9df1a6d9b02267e4902
